name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.8.0
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_API_BASE_URL: https://api.sumologic.com
      BATON_API_ACCESS_ID: ${{ secrets.API_ACCESS_ID }}
      BATON_API_ACCESS_KEY: ${{ secrets.API_ACCESS_KEY }}
      BATON_INCLUDE_SERVICE_ACCOUNTS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install baton
        uses: ConductorOne/github-workflows/actions/get-baton@v2
      - name: Build baton-sumo-logic
        run: go build ./cmd/baton-sumo-logic
      - name: Grant/revoke
        uses: ConductorOne/github-workflows/actions/sync-test@v2
        with:
          connector: ./baton-sumo-logic
          baton-entitlement: "role:0000000000C060EA:assigned"
          baton-principal: "0000000000C3D49D"
          baton-principal-type: user
      - name: Test Account Provisioning
        uses: ConductorOne/github-workflows/actions/account-provisioning@v3
        with:
          connector: ./baton-sumo-logic
          account-email: "test-${{ github.run_id }}@example.com"
          account-profile: >-
            {
              "email": "test-${{ github.run_id }}@example.com",
              "first_name": "Baton",
              "last_name": "CI-Test",
              "default_role_id": "0000000000C05D05"
            }
