name: ci
on: pull_request
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run linters
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=3m
  go-test:
    strategy:
      matrix:
        go-version: [1.24.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: go tests
        run: (set -o pipefail && go test -v -covermode=count -json ./... | tee test.json)
      - name: annotate go tests
        if: always()
        uses: guyarb/golang-test-annotations@v0.5.1
        with:
          test-results: test.json

  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      BATON_API_BASE_URL: https://api.sumologic.com
      BATON_API_ACCESS_ID: ${{ secrets.API_ACCESS_ID }}
      BATON_API_ACCESS_KEY: ${{ secrets.API_ACCESS_KEY }}
      BATON_INCLUDE_SERVICE_ACCOUNTS: true
      # This is the display name of the account and we use it to check if the account was created.
      ACCOUNT_DISPLAYNAME: 'first-name-test last-name-test'
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build baton-sumo-logic
        run: go build ./cmd/baton-sumo-logic

      - name: Create account
        env:
          CREATE_ACCOUNT_FLAGS: >-
            --create-account-email="testConductorOn@test.com"
            --create-account-profile='{"email":"testConductorOn@test.com","first_name":"first-name-test","last_name":"last-name-test","default_role_id":"0000000000C05D05"}'
        run: ./baton-sumo-logic ${{ env.CREATE_ACCOUNT_FLAGS }}

      - name: Check account was created
        id: check_account
        run: |
          ./baton-sumo-logic
          CREATED_ACCOUNT_ID=$(./baton-sumo-logic principals --output-format=json | jq -r --arg name "${{ env.ACCOUNT_DISPLAYNAME }}" '.resources[] | select(.resource.displayName == $name) | .resource.id.resource')
          echo "account_id=$CREATED_ACCOUNT_ID" >> $GITHUB_OUTPUT
          [ -n "$CREATED_ACCOUNT_ID" ]

      - name: Delete account
        run: ./baton-sumo-logic --delete-resource "${{ steps.check_account.outputs.account_id }}" --delete-resource-type "user"

      - name: Check account was deleted
        run: ./baton-sumo-logic && ./baton-sumo-logic principals --output-format=json | jq -e --arg name "${{ env.ACCOUNT_DISPLAYNAME }}" '.resources | map(select(.resource.displayName == $name)) | length == 0'

 